qtpyvcp/vcp_chooser/vcp_chooser.py

Issue10 robustify vcp chooser

---

examples/probe_basic/menubar.yml
examples/probe_basic_latc/menubar.yml
examples/probe_basic_lathe/menubar.yml
examples/probe_basic_vertical/menubar.yml
qtpyvcp/actions/program_actions.py
qtpyvcp/yaml_lib/default_menubar.yml

While not really necessary as the loaded file is monitored for changes.
The menu item should work or be removed.

BUG: Fix reload menu item

---

qtpyvcp/widgets/hal_widgets/designer_plugins.py
qtpyvcp/widgets/hal_widgets/hal_plot.py

New HAL plot wiget that can plot up to 4 HAL pin inputs as a scrolling time plot. Configurable plot series pens and the legend can be enables or disabled as required.

ENH: add HalPlot widget

---

qtpyvcp/actions/__init__.py
qtpyvcp/widgets/input_widgets/action_dial.py
qtpyvcp/widgets/input_widgets/designer_plugins.py

simple VCP Action Dial

---

MANIFEST.in

add qml files to pip installs

---

qtpyvcp/plugins/status.py
qtpyvcp/widgets/input_widgets/mdihistory_widget.py

1. able to move MDI entries up and down the list via two new slots
2. backed the up/down movement GCode Editor for use as a mini program.  It copies content across into a tmp file. It does NOT copy into the editor at a point like copy/paste.  That could be a future enhancement.
3. increased heart beat rate from 1/sec to 4/sec.

ENH: Mdi history enhance2

---

qtpyvcp/widgets/display_widgets/vtk_backplot/vtk_backplot.py

Fix 3D plot exceptions without file loaded

---

qtpyvcp/widgets/dialogs/about_dialog.py
qtpyvcp/widgets/dialogs/error_dialog.py
qtpyvcp/widgets/dialogs/offsets_dialog.py
qtpyvcp/widgets/dialogs/tool_edit_dialog.py

All dialogs stay on top

---

qtpyvcp/app/application.py
qtpyvcp/app/launcher.py
qtpyvcp/lib/native_notification.py
qtpyvcp/plugins/__init__.py
qtpyvcp/plugins/base_plugins.py
qtpyvcp/plugins/notifications.py

This adds a second init function to plugins that need the main window to be loaded like notifications
this come to be the solution for #51 
I only need to know the correct place to call ```postGuiInitialisePlugins()```

(Notifications) post-gui plugin initialize

---

qtpyvcp/widgets/display_widgets/vtk_backplot/vtk_backplot.py

Set the azimuth (x-axis rotation with the mouse) always around the upright position (0, 0, 1). This feels much more natural and avoid getting lost in 3-dimensional rotation with a 2-dimensional input device like a mouse.
Before this PR, getting lost:
New, azimuth against upright position:

vtk_backplot: use an upright view up vector for azimuth

---

qtpyvcp/widgets/display_widgets/vtk_backplot/linuxcnc_datasource.py
qtpyvcp/widgets/display_widgets/vtk_backplot/vtk_backplot.py

Fixed clipping range for inch machines

Fixed datasource in designer mode

---

.gitignore
qtpyvcp/widgets/input_widgets/mdihistory_widget.py

Per request from Lcvette have added Designer option to allow the list to either have the latest entered MDI command at the top or bottom.  Adjusted internal processing to accommodate for this.

MDI History Natural Order Option

---

qtpyvcp/widgets/form_widgets/main_window.py

This matches the Axis UI which provides max-speed jogging when holding
shift when jogging via the keyboard.

Added keyboard modifier (Shift) to toggle rapid jog.

---

qtpyvcp/widgets/input_widgets/gcode_text_edit.py

Corrected iterator issue that to align with pyqt docs.

MNT: iterator compatibility issue

---

qtpyvcp/widgets/base_widgets/base_widget.py

This property allows setting a security level on each VCP widget from within Designer.  This will support a security feature (probably as a plugin) that will allow the dynamic enable/disable of vcp widgets bassed on the signed in user's security level.

Implementation of security property

---

qtpyvcp/plugins/user_managment.py

Now references a user.txt file for users, password and security level per user. Added extra log entries.

Extension and bug fix.

---

qtpyvcp/widgets/display_widgets/vtk_backplot/vtk_backplot.py

Extended the viewprogram method to allow non perspective views to be accessed.

ENH:Extended set ViewProgram to be able to do different view types.

---

qtpyvcp/utilities/info.py

Added new INFO function to return the min/max limits on axis (not joints) using the normal axis letter notation per ini file.  e.g. [AXIS_X] MIN_LIMIT= -1

ENH INFO for getAxisMinMax

---

qtpyvcp/widgets/display_widgets/vtk_backplot/vtk_backplot.py

Enhanced VTK set prog view on load to also support a default view other than P.

Extended VTK to allow default program view loading beyond P

---

qtpyvcp/widgets/input_widgets/gcode_text_edit.py

Also template for possible syntax highlighing on/off slot.

ENH: Completed SaveFile

---

qtpyvcp/tools/editvcp.py

Signed-off-by: Alec Ari <neotheuser@ymail.com>

Fix Gentoo error

---

src/qtpyvcp/widgets/dialogs/toolchange_dialog.py

Do not close dialog until `changed` hal pin is de-asserted. Use a polling timer to ensure consistent state.

Fix race condition bug on manual tool change dialog

---

src/qtpyvcp/actions/__init__.py
src/qtpyvcp/actions/power_actions.py
src/qtpyvcp/widgets/dialogs/shutdown_dialog.py
src/qtpyvcp/widgets/dialogs/shutdown_dialog.ui
src/qtpyvcp/yaml_lib/default_config.yml
src/qtpyvcp/yaml_lib/default_menubar.yml

My first pull request for this project.  Be nice.
I added a action that can be called to shutdown the computer.
shut_system_down_prompt() method, which invokes xfce4-session-logout and if that fails, fails back to 'systemctl poweroff'
shut_system_down_now()  which invokes 'xfce4-session-logout -h'  and if that fails, fails back to 'systemctl poweroff'
Made a dialog 'shutdown_dialog.ui' that has a cancel and shutdown button to confirm the shutdown.  stay_on_top=True, frameless=True 
Please let me know if this is the correct approach to this.

Shutdown dialog

---

src/qtpyvcp/widgets/input_widgets/file_system.py

修复中文用户获取时间报错问题
Fixed the issue of Chinese users getting time error

更新 file_system.py

---

src/qtpyvcp/widgets/display_widgets/vtk_backplot/machine_actor.py
src/qtpyvcp/widgets/display_widgets/vtk_backplot/vtk_backplot.py

Adds ability to set the color of machine components
Adds settings to the ini file that allow the perspective view direction to be set

Backplot cosmetics
