qtpyvcp/vcp_chooser/vcp_chooser.py

This fixes issue #7 where yaml.load issues the following warning:
92: YAMLLoadWarning: calling yaml.load() without Loader=... is
deprecated, as the default Loader is unsafe. Please read
msg.pyyaml.org/load for full details.
Ref:
https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

BUG: Silence yaml.load() warning

---

examples/probe_basic/menubar.yml
examples/probe_basic_latc/menubar.yml
examples/probe_basic_lathe/menubar.yml
examples/probe_basic_vertical/menubar.yml
qtpyvcp/actions/program_actions.py
qtpyvcp/yaml_lib/default_menubar.yml
sim/example_gcode/blank.ngc

This doesn't work for installs where
/home/kurt/dev/cnc/qtpyvcp/sim/example_gcode/blank.ngc
does not exist.
This commit changes to a temporary generated file.

BUG: The close menu item uses a hardcoded path

---

.gitignore
qtpyvcp/__init__.py
qtpyvcp/plugins/status.py
qtpyvcp/widgets/input_widgets/designer_plugins.py
qtpyvcp/widgets/input_widgets/mdientry_widget.py
qtpyvcp/widgets/input_widgets/mdihistory_widget.py

MDI History/Queue Widget for use in Designer. (v1)
Purpose/Features:
[1] Supports display of the MDI history and selecting items from that history for running.
[2] Supports stacking up MDI commands while an existing MDI is being executed.  MDI command in flight has a "play" triangle icon beside it.  Waiting commands have a "pause" icon beside them.
[3] supports run from selected line/row via Slot
[4] supports clearing queued to run (i.e. "paused") MDI commands via Slot
[5] uses QTimer to create a 1 second heart beat to process commands
[6] supports pause of queue processing via Slot
Key changes made to existing works:
status.py:  commented out code to "remove" entry of duplicate commands.  For queue to work effectively from a usability angle you need to be able to add duplicate commands. …

Mdi history and queue widget

---

qtpyvcp/plugins/status.py

Simple fix to resolve rule triggers on stacked (and possibly other?) widgets not behaving correctly for essentially static data items.  i.e. those coming from the ini/config files.  The behaviour indicated that either the rule was not firing (unlikely) or was firing at a point in time when either the widget was not initialised or was not responding to the index value change.
Added a method to status.py that is called at the very end of the initalize() method to allow us to set to None any channel items that are static and benefit from a forced reload.
This is a work around but one that is contained and can be easily backed out later if root cause is found and solved.

Static status gui interaction

---

qtpyvcp/plugins/exported_hal.py
qtpyvcp/yaml_lib/default_config.yml

This is intended to be a simple and light weight way to expose HAL pins of limited core linuxcnc functions/actions so that VCP developers get some stuff for free.

Plugin to export specifc HAL pins and associated linuxcnc action.

---

qtpyvcp/widgets/base_widgets/bar_indicator.py

Corrected logic to deal with border display based on orientation. Removed trying to rotate text in vertical display. Removes need to traying to deal with width issues and working out correct bar width to display text as it widens as percentage climbs to 100%.
ToDo: It may be possible to get the text displayed in horizontal form when bar is vertical. But that is not immediately obvious and could become a timesink "blocker" when the widget is perfectly usable and useful as is.

BUG: Corrected shading for vertical orirentation.

---

qtpyvcp/widgets/input_widgets/setting_slider.py

Clearing the text value when the desired value equals the default value
causes an issue when using the control as the value for a parameter in
an ngc call since the SubCallButton uses the text value of the control
as the parameter value. In this scenario there is no way to use the
default value as the settings actual value (that I know of) since the control sets the
text to ''.
Thanks for the amazing work on qtpyvcp and probe_basic. It is very much appreciated.

BUG: Do not clear text value when default is used

---

qtpyvcp/actions/machine_actions.py

Problem:
- The _jog_axis_ok method disallows jogging if the joint has hit a limit even
if override limits is active.
Solution:
- If the axis has hit a limit, check if override_limits has been enabled for
the corresponding joint. If so, jogging is ok.
NB: This should fix https://github.com/kcjengr/probe_basic/issues/16

BUG: Allow jog on limit when limit override is true

---

qtpyvcp/widgets/base_widgets/eval_line_edit.py
qtpyvcp/widgets/input_widgets/dro_line_edit.py
qtpyvcp/widgets/input_widgets/eval_line_edit.py
setup.py

ENH: Allow arithmetic expressions in DROLineEdit
Problem:
- It is often useful to be able to set the current work offset for
an axis using an expression (ex. 120/25.4, or just /2 to divide
the current offset by 2).
Solution:
- Create a new EvalLineEdit class that will invoke the eval operator
on the current text and have DROLineEdit inherit from it.
- If the expression starts with an operator it is applied to
the current value for this DRO. For example, entering '/2' into
the DROLineEdit will divide the current value by 2.
- If the expression is valid, the text will be set to the result.
Otherwise, the expression is left as is.
NB: Any control that wants to evaluate arithmetic expressions can
inherit from EvalLineEdit, and gain that functionality. No other
changes are required for the …

ENH: Allow arithmetic expressions in DROLineEdit

---

qtpyvcp/widgets/display_widgets/vtk_backplot/vtk_backplot.py

vtk_backplot: enable anti-aliasing

---

qtpyvcp/widgets/display_widgets/vtk_backplot/vtk_backplot.py

From https://stackoverflow.com/questions/51357630/vtk-rendering-not-working-as-expected-inside-pyqt?rq=1#comment89720589_51360335.

vtk_backplot: fix wrongly visible backfaces on Linux with Intel video card

---

qtpyvcp/widgets/input_widgets/dro_line_edit.py

Resolves issue #72.
DROLineEdit will stop updating when user starts editing, until either the commanded position changes or the user presses the escape key with the lineEdit in focus.

DROLineEdit stops updating when being edited.

---

qtpyvcp/widgets/input_widgets/mdientry_widget.py
qtpyvcp/widgets/input_widgets/mdihistory_widget.py

FEATURE: MDIHistory and MDILineEntry did not play nicely together.
When pushing the return key after keyboard entry of gcode while the item would execute it would appear as a blank line in the MDIHistory widget. This was caused by the keypress support in MDILine executing the command itself and not passing it to MDIHistory to manage.  This pull request fixes that by having MDIHistory set a flag on the MDILine. This flag is tested to determine how MDILine should react to return-key presses.
FEATURE: The highlighting of newly entered items into MDIHistory and executing items was not necessarily obvious or consistent. So now the last entered item is highlighted via the selected highlight colour on the ListWidget. The currently executing line is also highlighted in the same manner along with …

Mdi history and mdi line rtn key behaviour

---

qtpyvcp/widgets/input_widgets/mdientry_widget.py

mdi_entry uses the completer feature to give a ui drop down of history entries. This makes sense when this widget us used standalone but may not be desirable if used in conjunction with mdi_history.  Added Designer boolean to suppress this behaviour.

FEATURE: Added designer boolean to remove completer behaviour

---

qtpyvcp/widgets/input_widgets/mdihistory_widget.py

A shallow copy of the framework STATUS mdi value list was being taken which meant changes to it were also happening to the framework managed list. Not what we wanted. This resulted in other changes being needed to support the potentially different list orders based on the mdi history natural-order flag.

BUG: Found shallow copy issue on mdi history

---

qtpyvcp/plugins/tool_table.py
qtpyvcp/widgets/qtdesigner/rules_editor.py

Adds a flute count datachannel.
Flute count is obtained from the remark in the tooltable. Any number preceding the letters "fl" (not case sensitive) will be taken as flute count, so "3fl" "3 fl" or "3 flute" all work.
With this datachannel it becomes possible to implement chipload displays in a VCP using the rules editor.

Flute count datachannel

---

qtpyvcp/widgets/button_widgets/subcall_button.py

The code for checking for the existence of an ngc subcall file would not exit where it should on fail due to missing intermediate var.

BUG #94 - Fix for subcall ngc file improper existence check

---

qtpyvcp/actions/machine_actions.py

Changed the Axis unhome to now scan and unhome each joint that is linked to the selected axis.
This ensures gantry machines that have a single axis associated with 2 joints are correctly dealt with.  This code should also cope with the situation where an axis with >1 joints associated with it will be correctly unhomed.

BUG: Unhome axis did not account for gantry 2 jnts to an axis

---

docs/source/install/bullseye.rst

Updated link to prevent this error using the previous unauthenticated 
git protocol:
fatal: remote error: 
The unauthenticated git protocol on port 9418 is no longer supported.
Please see 
https://github.blog/2021-09-01-improving-git-protocol-security-github/ 
for more information.

DOC: fix github link to linuxcnc project

---

docs/source/install/bullseye.rst

Fixes some minor typo's and capitalization in `docs/source/install/bullseye.rst`
Simplified creating and traversing directories in section about getting LinuxCNC source code. I also removed the part where you configured and built the source code. If the goal is to create the .deb packages, that's unnecessary.
If I'm wrong, I hope it can be made more specific, and perhaps split it up in it's own section.

Documentation

---

src/qtpyvcp/widgets/dialogs/toolchange_dialog.py
src/qtpyvcp/widgets/dialogs/toolchange_dialog.ui

Add basic functionality for manual tool changing via dialog, similar to the one built into qtvcp. It displays the tool number and tool remark from the tool table to aid the operator in finding the tool. It implements the same interface as the `hal_manualtoolchange` component, but in a different namespace.

Add basic dialog for manual tool changing

---

debian/control

this is needed to allow `editvcp` to work in non dev install

Add python3-distro as Depends

---

src/qtpyvcp/widgets/input_widgets/file_system.py

Modified loadSelectedFile in file_system.py so that it does the same thing as openSelectedItem instead of just loading g-code.  This makes it possible to Relabel the"Load G-Code" Button to "Select Folder" when a folder has been selected.  This makes the main file manager more touch screen friendly.

Load g code button change

---

src/qtpyvcp/ops/base_op.py

For conversational operations, base_op.py  compares the text values from the pulldown to know if to use M7 or M8.  As a result, if you call them something else such as air blast, vacuum, or if you want to toggle both, then it wouldn't work.  Added these options in.  Not sure if it's possible to do this a different way so that other people can change the values, I.E. instead of vacuum, they could use dust hood or something.

Add support for air blast, vacuum & both for M7 & M8.

---

src/qtpyvcp/widgets/display_widgets/vtk_backplot/vtk_backplot.py
src/qtpyvcp/yaml_lib/default_config.yml

active_wc_index can sometimes be set to -1. I think this is a timing issue, as it dervies this value from _status.stat.g5x_index In getActiveWcsIndex() method, it returns self._status.stat.g5x_index -1 If _status.stat.g5x_index is 0 because it's not been initialized from linuxcnc yet, then it will return -1, which breaks the views.
Add Machine EXT View for default / persistant view optin in yaml file.
** ToDo ** Add avility to set BASE scale value for setViewMachine and/or maybe default zoom level

Fix timing issue with active_wc_index

---

src/qtpyvcp/tools/plasma_gcode_preprocessor.py

Hello,
I just installed a Debian package of 5.0.2 and got these messages:
```
/usr/lib/python3/dist-packages/qtpyvcp/tools/plasma_gcode_preprocessor.py:294: SyntaxWarning: invalid escape sequence '\s'
f = re.findall("T\s*\d+|M6", line.upper().strip())
/usr/lib/python3/dist-packages/qtpyvcp/tools/plasma_gcode_preprocessor.py:341: SyntaxWarning: invalid escape sequence '\('
s = re.split(";|\(", line, 1)
/usr/lib/python3/dist-packages/qtpyvcp/tools/plasma_gcode_preprocessor.py:359: SyntaxWarning: invalid escape sequence '\('
s = re.split(";|\(",self.raw[1:],1)
/usr/lib/python3/dist-packages/qtpyvcp/tools/plasma_gcode_preprocessor.py:360: SyntaxWarning: invalid escape sequence '\('
robj = re.search(";|\(",self.raw[1:])
/usr/lib/python3/dist-packages/qtpyvcp/tools/plasma_gcode_preprocessor.py:4 …
```

regular expressions with raw strings
